---
title: "Daily/2021/03/07"
date: 2021-03-07T22:30:59+09:00
tags: ["logs"]
---

# Private Repository の go get ができない

go get でこんなエラーが出た。

```
        fatal: 'origin' does not appear to be a git repository
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
```

同じ org の別リポジトリを go get してもエラーにならないのになんで・・・？  
検索したら、それっぽいのあった。

https://qiita.com/yagrush/items/ddcbc718d1c6f60c0aac

> 一部モジュールのチェックサムがおかしくなってしまったようです…

そういえばなんとなく依存解決してくれてるけど、 go mod がどんなディレクトリを掘ってどこに認証情報を持ってるとか、その辺考えてなかったな、、  
というか、認証情報とかがキャッシュされてるの気づかなかった。毎回とってるもんかと。どこかで時間とれれば勉強したい・・・

ということで、

```
$ go clean -modcache
$ go get -u
```

をやったら治りました。超助かりました。

# その他

# Next
